version: '3'

services:
  db:
    image: postgres
    networks:
      - movie_net
    container_name: movie-db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie
    expose:
      - 5432
    ports:
      - "5432:5432"

  movie-app:
    image: tahalechgar/movie
    networks:
      - movie_net
    container_name: movie-app
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - db

  recommendation-app:
    image: tahalechgar/recommendations
    networks:
      - movie_net
    container_name: recommendation-app
    ports:
      - "8081:8081"

networks:
  movie_net:
    driver: bridge